import fitz  # PyMuPDF

doc = fitz.open()

# --- Page 1: Dengue Fever ---
page = doc.new_page()
tw = fitz.TextWriter(page.rect)
tw.append((50, 60), "DENGUE FEVER", font=fitz.Font("helv"), fontsize=18)
tw.append((50, 90), "Overview", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 110), "Dengue fever is a mosquito-borne tropical disease caused by the dengue virus.", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 130), "It is transmitted by Aedes mosquitoes, primarily Aedes aegypti.", font=fitz.Font("helv"), fontsize=11)

tw.append((50, 170), "SYMPTOMS", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 190), "High fever (40°C / 104°F)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 210), "Severe headache, especially in the forehead", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 230), "Pain behind the eyes (retro-orbital pain)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 250), "Muscle and joint pain (breakbone fever)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 270), "Nausea and vomiting", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 290), "Skin rash (maculopapular) appearing 2-5 days after fever onset", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 310), "Mild bleeding from nose or gums", font=fitz.Font("helv"), fontsize=11)

tw.append((50, 350), "WARNING SIGNS - SEEK IMMEDIATE CARE", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 370), "Severe abdominal pain or tenderness", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 390), "Persistent vomiting (3 or more episodes in 24 hours)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 410), "Clinical fluid accumulation (ascites, pleural effusion)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 430), "Mucosal bleeding (gums, nose, urine, stool)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 450), "Liver enlargement > 2 cm", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 470), "Rising hematocrit with rapid platelet drop", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 490), "Lethargy, restlessness, or irritability", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 510), "Rapid breathing or respiratory distress", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 530), "Cold, clammy skin or cyanosis", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 550), "These warning signs indicate possible dengue hemorrhagic fever or dengue shock syndrome.", font=fitz.Font("helv"), fontsize=10)

tw.append((50, 590), "PREVENTION", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 610), "Use mosquito repellent containing DEET, picaridin, or IR3535", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 630), "Sleep under insecticide-treated bed nets", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 650), "Wear long-sleeved shirts and long pants, especially during daytime", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 670), "Eliminate standing water where mosquitoes breed (flower pots, tires, containers)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 690), "Cover water storage containers tightly", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 710), "Use window and door screens", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 730), "Support community mosquito control programs", font=fitz.Font("helv"), fontsize=11)

tw.append((50, 770), "TREATMENT", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 790), "There is no specific antiviral treatment for dengue fever.", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 810), "Rest and drink plenty of fluids to prevent dehydration.", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 830), "Acetaminophen (paracetamol) can be used for fever and pain.", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 850), "Avoid aspirin and NSAIDs (ibuprofen) as they increase bleeding risk.", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 870), "For severe dengue, hospitalization with IV fluids and careful monitoring is required.", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 890), "Monitor platelet count closely during the critical phase (days 3-7).", font=fitz.Font("helv"), fontsize=11)
tw.write_text(page)

# --- Page 2: Diabetes ---
page = doc.new_page()
tw = fitz.TextWriter(page.rect)
tw.append((50, 60), "DIABETES MELLITUS", font=fitz.Font("helv"), fontsize=18)
tw.append((50, 90), "Overview", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 110), "Diabetes is a chronic metabolic condition characterized by elevated blood glucose levels.", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 130), "It affects how the body processes blood sugar (glucose).", font=fitz.Font("helv"), fontsize=11)

tw.append((50, 170), "SYMPTOMS", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 190), "Excessive thirst (polydipsia)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 210), "Frequent urination (polyuria)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 230), "Unexplained weight loss", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 250), "Fatigue and weakness", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 270), "Blurred vision", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 290), "Slow-healing wounds or sores", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 310), "Tingling or numbness in hands or feet (neuropathy)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 330), "Dry, itchy skin", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 350), "Frequent infections (skin, gum, bladder, vaginal)", font=fitz.Font("helv"), fontsize=11)

tw.append((50, 390), "TYPE 1 vs TYPE 2 DIABETES", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 410), "Type 1: Autoimmune condition. The immune system attacks insulin-producing beta cells", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 430), "in the pancreas. Results in little or no insulin production. Usually diagnosed", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 450), "in childhood or young adulthood. Requires lifelong insulin therapy.", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 480), "Type 2: Body becomes resistant to insulin or pancreas produces insufficient insulin.", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 500), "Accounts for 90-95% of diabetes cases. Strongly linked to obesity, sedentary", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 520), "lifestyle, and family history. Can often be managed with lifestyle changes", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 540), "and oral medications, though insulin may eventually be needed.", font=fitz.Font("helv"), fontsize=11)

tw.append((50, 580), "COMPLICATIONS", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 600), "Cardiovascular disease: heart attack, stroke, atherosclerosis", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 620), "Diabetic nephropathy: kidney damage potentially leading to dialysis", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 640), "Diabetic retinopathy: eye damage potentially leading to blindness", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 660), "Diabetic neuropathy: nerve damage causing pain, numbness, digestive issues", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 680), "Foot complications: poor circulation, infections, potential amputation", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 700), "Skin conditions: bacterial and fungal infections", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 720), "Hearing impairment", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 740), "Alzheimer's disease: increased risk", font=fitz.Font("helv"), fontsize=11)

tw.append((50, 780), "MANAGEMENT", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 800), "Monitor blood glucose levels regularly", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 820), "Follow a balanced diet low in refined sugars and processed foods", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 840), "Exercise regularly (150 minutes per week of moderate activity)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 860), "Maintain a healthy weight (BMI 18.5-24.9)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 880), "Take medications as prescribed", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 900), "Regular checkups: eye exams, kidney function, foot examinations", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 920), "HbA1c target: generally below 7%", font=fitz.Font("helv"), fontsize=11)
tw.write_text(page)

# --- Page 3: Hypertension ---
page = doc.new_page()
tw = fitz.TextWriter(page.rect)
tw.append((50, 60), "HYPERTENSION (HIGH BLOOD PRESSURE)", font=fitz.Font("helv"), fontsize=18)
tw.append((50, 90), "Overview", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 110), "Hypertension is a chronic medical condition where blood pressure in the arteries is", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 130), "persistently elevated. It is often called the 'silent killer' because it typically", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 150), "has no symptoms but can lead to serious health problems if untreated.", font=fitz.Font("helv"), fontsize=11)

tw.append((50, 190), "BLOOD PRESSURE CLASSIFICATION", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 210), "Normal: Less than 120/80 mmHg", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 230), "Elevated: 120-129 / less than 80 mmHg", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 250), "Stage 1 Hypertension: 130-139 / 80-89 mmHg", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 270), "Stage 2 Hypertension: 140 or higher / 90 or higher mmHg", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 290), "Hypertensive Crisis: Higher than 180 / higher than 120 mmHg (seek emergency care)", font=fitz.Font("helv"), fontsize=11)

tw.append((50, 330), "RISK FACTORS", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 350), "Age (risk increases with age)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 370), "Family history of hypertension", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 390), "Being overweight or obese", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 410), "High sodium (salt) diet", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 430), "Low potassium diet", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 450), "Physical inactivity", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 470), "Excessive alcohol consumption", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 490), "Tobacco use", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 510), "Chronic stress", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 530), "Certain chronic conditions (diabetes, kidney disease)", font=fitz.Font("helv"), fontsize=11)

tw.append((50, 570), "LIFESTYLE MODIFICATIONS", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 590), "Reduce sodium intake to less than 2,300 mg per day (ideally 1,500 mg)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 610), "Follow the DASH diet (Dietary Approaches to Stop Hypertension)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 630), "Exercise regularly: at least 150 minutes per week of moderate aerobic activity", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 650), "Maintain a healthy weight (BMI 18.5-24.9)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 670), "Limit alcohol: no more than 2 drinks/day for men, 1 for women", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 690), "Quit smoking and avoid secondhand smoke", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 710), "Manage stress through relaxation techniques, meditation, or yoga", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 730), "Monitor blood pressure at home regularly", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 750), "Get 7-9 hours of quality sleep per night", font=fitz.Font("helv"), fontsize=11)

tw.append((50, 790), "COMPLICATIONS OF UNCONTROLLED HYPERTENSION", font=fitz.Font("helv"), fontsize=14)
tw.append((50, 810), "Heart attack and heart failure", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 830), "Stroke (ischemic or hemorrhagic)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 850), "Chronic kidney disease and kidney failure", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 870), "Vision loss (hypertensive retinopathy)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 890), "Peripheral artery disease", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 910), "Aneurysm (weakening of artery walls)", font=fitz.Font("helv"), fontsize=11)
tw.append((50, 930), "Cognitive decline and vascular dementia", font=fitz.Font("helv"), fontsize=11)
tw.write_text(page)

doc.save("C:/coding/medical RAG/data/pdfs/medical_handbook.pdf")
doc.close()
print("Demo PDF created: medical_handbook.pdf")
